### ISSUE TITLE
Missing variables + missing loop?

### ISSUE THREAD

**Issue by WakeCaine** [PaoloConte/smooth-line-chart#2]
madigun697 submitted code without reviewing it and forgot variables and possibly loop he/she used while setting text.
Current version is not working. I propose reverting to old version(do tag for release) and putting this on the branch to be fixed.

Missing variables:
- tPaint
- todayPoint
- i used when textCaptionEnable is true

Possibly there could be more missing parts.

**Comment by PaoloConte** [comment]
Hello,
thanks for pointing this out, I didn't review the submitted code. 
I reverted the commit, then maybe madigun697 will submit a proper patch
