### ISSUE TITLE
Can we add multiple lines(sets) in just one line chart

### ISSUE THREAD

**Issue by apoorv1031** [PaoloConte/smooth-line-chart#4]
The present code allows us to add one line in a chart, could you please help in adding an additional line in a single chart. The design of the chart is great so if you could just help me out with my problem.

**Comment by PaoloConte** [comment]
Hello,
I made a quick and dirty implementation and pushed it on a new branch 'multiple-lines'
Check it out!

Thanks

**Comment by apoorv1031** [comment]
Really appreciate the help. Thanks a lot. :)
