### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by Jay-Bruh** [PaoloConte/smooth-line-chart#5]
Hi, I cannot find the gradle file where you mention the dependencies. Can u tell me the implementation code please

**Comment by PaoloConte** [comment]
Hi Jay,
this is a very old project with an old structure, so there is no gradle file, but there are no special dependencies required in addition to the standard android ones.
You can create a new app in Android Studio and then add either SmoothLineChart.java or SmoothLineChartEquallySpaced.java to your project

**Comment by Jay-Bruh** [comment]
Ok Thanks!!
